[tox]
env_list =
    py311
minversion = 4.29.0

[flake8]
extend-ignore = E203
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist,.venv,.tox
max-complexity = 10
max-line-length = 120

[mypy]
strict = true

[testenv]
description = run the tests with pytest
package = editable
deps =
    pytest>=6
    pytest-cov
commands =
    pytest {tty:--color=yes} --cov=storage_tracker --cov-report=term-missing {posargs}

[testenv:flake8]
commands =
    flake8 storage_tracker

[testenv:mypy]
deps =
    mypy
    sqlmodel
    fastapi
commands =
    mypy storage_tracker
