[tox]
env_list =
    py311
minversion = 4.29.0

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
commands =
    pytest {tty:--color=yes} {posargs}

[flake8]
extend-ignore = E203
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist,.venv,.tox
max-complexity = 10
max-line-length = 120
